# Generated by Django 5.2.9 on 2026-03-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0003_tag_post_tags_collectionlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("content", models.TextField(blank=True, default="")),
                ("link", models.URLField()),
                ("time", models.DateTimeField()),
            ],
        ),
    ]
