# Generated by Django 6.0.3 on 2026-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_description',
            field=models.CharField(blank=True, help_text='Image description', max_length=255, null=True),
        ),
    ]
