# Generated by Django 6.0.3 on 2026-03-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_post_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
