# Generated by Django 6.0.3 on 2026-03-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_create_missing_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
