# Generated by Django 5.2.12 on 2026-03-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0010_alter_userprofile_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="saved_by",
        ),
    ]
